### ISSUE TITLE
No warning for the extension ctype

### ISSUE THREAD

**Issue by qpeyramale** [simmstein/t411-console#1]
Hello,

Afert first install on FreeBSD, I got this on login:
`Fatal error: Call to undefined function Symfony\Component\Yaml\ctype_digit() in /mnt/Apps/t411-console/vendor/symfony/yaml/Inline.php on line 124`

I just install php55-ctype and it work fine now. But a warning before would be nice. :)

Awsome program!
Regards

**Comment by simmstein** [comment]
These packages depend the distribution. For example, Debian does not make a specific package for ctype.
il will update the README!

Thanks :)

**Comment by qpeyramale** [comment]
Ok nice, thank you!

**Comment by simmstein** [comment]
Wait for php7. Fatal errors will throw an EngineException exception.
