### ISSUE TITLE
Sorting search list

### ISSUE THREAD

**Issue by qpeyramale** [simmstein/t411-console#2]
Hi,

Is it possible to sort the result by number of seed?

Thank you

**Comment by simmstein** [comment]
Hello, 

The API does not contain a method for sorting results. 
I can add an option to sort the torrents but it will be efficient only for the displayed results.

**Comment by simmstein** [comment]
The options `--sort` and `--asc` have been added.

**Comment by qpeyramale** [comment]
Great, it's very nice!
I'll just increase the limit for sorting on every result it could find.

Thank you very much!
